# Generated by Django 4.2.7 on 2025-10-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order', 'category', '-proficiency']},
        ),
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)'),
        ),
    ]
