# Generated by Django 4.2.7 on 2025-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, help_text='Upload an image or video file', null=True, upload_to='project_images/'),
        ),
    ]
