# Generated by Django 4.2.7 on 2025-10-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='Enter the URL of your profile image', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='Enter the URL of your project image or video', null=True),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.URLField(help_text='Enter the URL of your media file'),
        ),
    ]
