# Generated by Django 4.2.7 on 2025-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_profile_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)'),
        ),
    ]
