# Generated by Django 4.2.7 on 2025-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_options_project_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.URLField(blank=True, help_text='Enter the Cloudinary URL of your resume (PDF)', null=True),
        ),
    ]
